# AEM Sites Optimizer Configuration
# A GitHub repo can have multiple sites associated with it. site_url should be a list of urls.

# Example:
# site_url:
#   - "https://your-site.com"
#   - "https://another-site.com"

site_url:
  - https://blog.adobe.com/
